# Generated by Django 3.2 on 2021-04-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bode',
            new_name='body',
        ),
    ]
